### ISSUE TITLE
Rubocop does not pick the ruby version from .ruby-version

### ISSUE THREAD

**Issue by avandecreme** [rubyide/vscode-ruby#130]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.2.3
- VS Code version: 1.10.2
- Operating System: Linux
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
The rubocop started by vscode should pick the ruby version from the .ruby-version file like it does when started from the command line.

### Actual behavior
It picks ruby parser 2.1 where the `&.` syntax is not known.

### Steps to reproduce the problem
Create a new ruby project with a .ruby-version file and enable rubocop. Use the `&.` syntax in a file.
A red warning appears with the message
```
[Syntax]
unexpected token error
(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)
```

**Comment by maschwenk** [comment]
We fixed this in the Atom Rubocop here, most likely has to do with not running the executable from the project root https://github.com/AtomLinter/linter-rubocop/pull/197

**Comment by rebornix** [comment]
@maschwenk thanks for your pointer, it's easier to integrate this feature as you already did the investigation and good work, thanks.

**Comment by rebornix** [comment]
@avandecreme you mentioned that running rubocop in VSCode should behave the same way as command line, in latest version I loaded the env from cmd line when activating the extension. Can you check if the problem is still there? Thanks in advance!

**Comment by shadowtftby** [comment]
@rebornix , yes problem still active.
vscode-ruby version: 0.16.0
Ruby version: 2.4.1
VS Code version:  1.20.1
Operating System: Ubuntu

.ruby-version:
2.4.1

config vscode:

``` "ruby.lint": {
        "ruby": {
            "unicode": true //Runs ruby -wc -Ku
        },
        "fasterer": true,
        "rubocop": {
            "inherit_from": "/home/xxx/Yandex.Disk/rubocop/rubocop.yml",
            "lint": true,
            "rails": true
        }
    },```

/home/xxx/Yandex.Disk/rubocop/rubocop.yml:

```AllCops:
  TargetRubyVersion: 2.4
Metrics/AbcSize:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false```

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
